//
// ChatUploadFileResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ChatUploadFileResponse: Codable {

    public var message: String?
    public var result: Bool?
    public var payload: MessageFile?

    public init(message: String?, result: Bool?, payload: MessageFile?) {
        self.message = message
        self.result = result
        self.payload = payload
    }


}

