//
// File.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct File: Codable {

    public var uuid: String?
    public var key: String?
    public var originalFilename: String?
    public var publicUrl: String?
    public var permalink: String?

    public init(uuid: String?, key: String?, originalFilename: String?, publicUrl: String?, permalink: String?) {
        self.uuid = uuid
        self.key = key
        self.originalFilename = originalFilename
        self.publicUrl = publicUrl
        self.permalink = permalink
    }

    public enum CodingKeys: String, CodingKey { 
        case uuid
        case key
        case originalFilename = "original_filename"
        case publicUrl = "public_url"
        case permalink
    }


}

