//
// MessageFile.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct MessageFile: Codable {

    public var uuid: String?
    public var url: String?
    public var thumbnailUrl: String?
    public var type: String?

    public init(uuid: String?, url: String?, thumbnailUrl: String?, type: String?) {
        self.uuid = uuid
        self.url = url
        self.thumbnailUrl = thumbnailUrl
        self.type = type
    }

    public enum CodingKeys: String, CodingKey { 
        case uuid
        case url
        case thumbnailUrl = "thumbnail_url"
        case type
    }


}

