//
// PasswordEdit.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PasswordEdit: Codable {

    public var password: String?
    public var currentPassword: String?
    public var passwordConfirmation: String?

    public init(password: String?, currentPassword: String?, passwordConfirmation: String?) {
        self.password = password
        self.currentPassword = currentPassword
        self.passwordConfirmation = passwordConfirmation
    }

    public enum CodingKeys: String, CodingKey { 
        case password
        case currentPassword = "current_password"
        case passwordConfirmation = "password_confirmation"
    }


}

