//
// PasswordEmail.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PasswordEmail: Codable {

    public var email: String?

    public init(email: String?) {
        self.email = email
    }


}

