//
// ProfileUpdateMyProfileResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ProfileUpdateMyProfileResponse: Codable {

    public var message: String?
    public var result: Bool?
    public var payload: User?

    public init(message: String?, result: Bool?, payload: User?) {
        self.message = message
        self.result = result
        self.payload = payload
    }


}

