//
// Settings.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Settings: Codable {

    public var settings: [Setting]?

    public init(settings: [Setting]?) {
        self.settings = settings
    }


}

